---
- name: Cowsay Module
  hosts: cowsay
  become: true
  remote_user: centos

  roles:
    - epel
    - cowsay
    - fortune
    - motd
- name: return motd to registered var
  command: cat /etc/motd
  
    