---
- name: Cowsay Module
  hosts: cowsay
  become: true
  remote_user: centos

  roles:
    - epel
    - cowsay
    - fortune
    - motd
    
  tasks:
    - name: return motd
      shell: "fortune"
      register: motd
    - debug: msg="{{ motd.stdout }}"

  
    