---
- name: Cowsay Module
  hosts: cowsay
  become: true
  remote_user: centos

  roles:
    - epel
    - cowsay
    - fortune
    - motd
    
  tasks:
    - name: return motd
      command: fortune | cowsay
      register: motd
    - debug: msg="{{ motd.stdout }}"
    - debug: msg="{{ motd.stderr }}"
  
    