---

# Install newest stable version of OpenSCAP.
# Package openscap-utils provides oscap.ssh (not needed on remote machines).

- name: Add OpenSCAP yum repo
  copy: src=openscapmaint-openscap-latest-epel-7.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: Install OpenSCAP packages on all machines.
  yum:
      name: "{{ packages }}"
  vars:
    packages:
    - openscap-scanner
    - openscap-utils
    - scap-security-guide


- name: Create oscap-user account on all machines.
  user: name="{{ oscap_user }}"
  when: oscap_user is defined

- name: Enable oscap-user to run openscap scanner as root.
  copy: src="99-{{ oscap_user }}"
        dest="/etc/sudoers.d/99-{{ oscap_user }}"
        owner=root group=root mode=0640
        force=no
  when: oscap_user is defined
  
- name: Run scan
  shell: "oscap xccdf eval --remediate --fetch-remote-resources --results results.xml --profile xccdf_org.ssgproject.content_profile_pci-dss /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml"
  become: yes
  become_user: "{{ oscap_user }}"
  when: oscap_user is defined
